/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package buscador;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author jalt2
 */
public class Buscador extends javax.swing.JPanel {
    private final String TEXTO_DEFECTO = " ¿Que quieres escuchar?";
    
    /**
     * Creates new form Buscador
     */
    public Buscador() {
        initComponents();
        txtBuscar.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txtBuscar.getText().equals(TEXTO_DEFECTO)) {
                    txtBuscar.setText("");
                    
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (txtBuscar.getText().isEmpty()) {
                    txtBuscar.setText(TEXTO_DEFECTO);
                    
                }
            }
        });
        
        // Detectar clics en el frame o cualquier otra parte
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Si el campo está vacío y no tiene foco, restaura el placeholder
                if (!txtBuscar.hasFocus() && txtBuscar.getText().isEmpty()) {
                    txtBuscar.setText(TEXTO_DEFECTO);   
                }
            }
        });
//        this.setImageBtn(this.btnBack, "Back.png");
//        escalarIconoAlTamano(this.btnBack);

        
    }
    
    private void setImageBtn(JButton btn, String root){
        URL url = getClass().getResource(root); // SIN /
        if (url == null) {
            System.out.println("No se encontró el recurso: " + root);
            return;
        }

        ImageIcon image = new ImageIcon(url);

        // Espera a que el botón tenga tamaño válido
        SwingUtilities.invokeLater(() -> {
            int width = btn.getWidth() > 0 ? btn.getWidth() : 32;
            int height = btn.getHeight() > 0 ? btn.getHeight() : 32;

            Icon icon = new ImageIcon(image.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH));
            btn.setIcon(icon);
            this.repaint();
        });
    }   
    
    private void escalarIconoAlTamano(JButton btn) {
        Icon iconoOriginal = btn.getIcon();
        if (iconoOriginal == null || !(iconoOriginal instanceof ImageIcon)) {
            return;
        }

        ImageIcon imagenOriginal = (ImageIcon) iconoOriginal;

        // Escalar cada vez que el botón cambie de tamaño
        btn.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                int ancho = btn.getWidth();
                int alto = btn.getHeight();

                if (ancho > 0 && alto > 0) {
                    Image imagenEscalada = imagenOriginal.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
                    btn.setIcon(new ImageIcon(imagenEscalada));
                }
            }
        });
    }

    public JTextField getTxtBuscar() {
        return txtBuscar;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBuscador = new javax.swing.JPanel();
        btnForward = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JButton();
        btnFavoritos = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBuscador.setBackground(new java.awt.Color(51, 51, 51));
        pnlBuscador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnForward.setBackground(new java.awt.Color(0, 153, 51));
        btnForward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Forward.png"))); // NOI18N
        btnForward.setBorder(null);
        pnlBuscador.add(btnForward, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 30, 30));

        txtBuscar.setBackground(new java.awt.Color(153, 153, 153));
        txtBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtBuscar.setText(" ¿Que quieres escuchar?");
        txtBuscar.setBorder(null);
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        pnlBuscador.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 230, 30));

        btnBuscar.setBackground(new java.awt.Color(0, 153, 51));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        pnlBuscador.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 50, 30));

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Back.png"))); // NOI18N
        jButton1.setBorder(null);
        pnlBuscador.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Search.png"))); // NOI18N
        pnlBuscador.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 30, 30));

        add(pnlBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnPerfil.setBackground(new java.awt.Color(0, 153, 51));
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/user.png"))); // NOI18N
        btnPerfil.setBorder(null);
        add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        btnFavoritos.setBackground(new java.awt.Color(0, 153, 51));
        btnFavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Favorite.png"))); // NOI18N
        btnFavoritos.setBorder(null);
        add(btnFavoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFavoritos;
    private javax.swing.JButton btnForward;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlBuscador;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
