
package buscador;

import control.ControlNavegacion;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author jalt2
 */
public class Buscador extends javax.swing.JPanel {
    private final String TEXTO_DEFECTO = " ¿Que quieres escuchar?";
    //private ControlNavegacion control;
    /**
     * Creates new form Buscador
     */
    ControlNavegacion control = ControlNavegacion.getInstance();

    public Buscador() {
        initComponents();
//        this.control=control;
        txtBuscar.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txtBuscar.getText().equals(TEXTO_DEFECTO)) {
                    txtBuscar.setText("");
                    
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (txtBuscar.getText().isEmpty()) {
                    txtBuscar.setText(TEXTO_DEFECTO);
                    
                }
            }
        });
        
        // Detectar clics en el frame o cualquier otra parte
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Si el campo está vacío y no tiene foco, restaura el placeholder
                if (!txtBuscar.hasFocus() && txtBuscar.getText().isEmpty()) {
                    txtBuscar.setText(TEXTO_DEFECTO);   
                }
            }
        });
//        this.setImageBtn(this.btnBack, "Back.png");
//        escalarIconoAlTamano(this.btnBack);
    }
    


    public JTextField getTxtBuscar() {
        return txtBuscar;
    }

    public JPanel getPnlBuscador() {
        return pnlBuscador;
    }
    
    

    public void setControl(ControlNavegacion control) {
        //this.control = control;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBuscador = new javax.swing.JPanel();
        btnForward = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnFavoritos = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBuscador.setBackground(new java.awt.Color(51, 51, 51));
        pnlBuscador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnForward.setBackground(new java.awt.Color(0, 153, 51));
        btnForward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Forward.png"))); // NOI18N
        btnForward.setBorder(null);
        btnForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForwardActionPerformed(evt);
            }
        });
        pnlBuscador.add(btnForward, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 30, 30));

        btnBack.setBackground(new java.awt.Color(0, 153, 51));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Back.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlBuscador.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 30));

        add(pnlBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnPerfil.setBackground(new java.awt.Color(0, 153, 51));
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/user.png"))); // NOI18N
        btnPerfil.setBorder(null);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        btnFavoritos.setBackground(new java.awt.Color(0, 153, 51));
        btnFavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Favorite.png"))); // NOI18N
        btnFavoritos.setBorder(null);
        btnFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritosActionPerformed(evt);
            }
        });
        add(btnFavoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(0, 153, 51));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 50, 30));

        txtBuscar.setBackground(new java.awt.Color(153, 153, 153));
        txtBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtBuscar.setText(" ¿Que quieres escuchar?");
        txtBuscar.setBorder(null);
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Search.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        btnHome.setBackground(new java.awt.Color(0, 153, 51));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        control.iniciarVerPerfil();
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        control.regresar();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritosActionPerformed
        // TODO add your handling code here:
        control.iniciarVerFavoritos();
    }//GEN-LAST:event_btnFavoritosActionPerformed

    private void btnForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForwardActionPerformed
        // TODO add your handling code here:
        control.adelantar();
    }//GEN-LAST:event_btnForwardActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        control.iniciarFlujo();
    }//GEN-LAST:event_btnHomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFavoritos;
    private javax.swing.JButton btnForward;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlBuscador;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
