/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inicio;

import control.ControlNavegacion;

/**
 *
 * @author jalt2
 */
public class ExplorarAlbumes extends javax.swing.JFrame {
    private ControlNavegacion controlNavegacion;
    /**
     * Creates new form ExplorarAlbumes
     */
    public ExplorarAlbumes(ControlNavegacion controlNavegacion) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controlNavegacion=controlNavegacion;
        this.pnlBuscador.setControl(controlNavegacion);
        this.controlNavegacion.agregarClickListeners(this, pnlBuscador.getTxtBuscar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbFiltroExplorar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        scrExplorar = new javax.swing.JScrollBar();
        btnFiltrar = new javax.swing.JButton();
        txtArtistaFiltro = new javax.swing.JTextField();
        cmbGeneros = new javax.swing.JComboBox<>();
        cmbFiltro = new javax.swing.JComboBox<>();
        pnlBuscador = new buscador.Buscador();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Explorar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 46, -1, -1));

        cmbFiltroExplorar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo", "Canciones", "Albumes", "Artistas", "Generos" }));
        cmbFiltroExplorar.setSelectedIndex(2);
        cmbFiltroExplorar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cmbFiltroExplorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFiltroExplorarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbFiltroExplorar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Albumes");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        jPanel1.add(scrExplorar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, 580));

        btnFiltrar.setBackground(new java.awt.Color(0, 153, 51));
        btnFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFiltrar.setText("Filtrar");
        jPanel1.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        txtArtistaFiltro.setText("Buscar en Artistas");
        jPanel1.add(txtArtistaFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        cmbGeneros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genero" }));
        jPanel1.add(cmbGeneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(69, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pnlBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(521, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFiltroExplorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltroExplorarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFiltroExplorarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> cmbFiltro;
    private javax.swing.JComboBox<String> cmbFiltroExplorar;
    private javax.swing.JComboBox<String> cmbGeneros;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private buscador.Buscador pnlBuscador;
    private javax.swing.JScrollBar scrExplorar;
    private javax.swing.JTextField txtArtistaFiltro;
    // End of variables declaration//GEN-END:variables
}
