/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package detalles;

import control.ControlNavegacion;

/**
 *
 * @author jalt2
 */
public class DetalleFavoritos extends javax.swing.JFrame {
    private ControlNavegacion control;
    /**
     * Creates new form DetalleFavoritos
     */
    public DetalleFavoritos(ControlNavegacion control) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.control=control;
        this.control.agregarClickListeners(this, pnlBuscador.getTxtBuscar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFavoritos = new javax.swing.JPanel();
        pnlBuscador = new buscador.Buscador();
        jLabel1 = new javax.swing.JLabel();
        pnlMisFavoritos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlElementosFav = new javax.swing.JPanel();
        cmbFiltroTipo = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFavoritos.setBackground(new java.awt.Color(51, 51, 51));
        pnlFavoritos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlFavoritos.add(pnlBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mis Favoritos");
        pnlFavoritos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        pnlMisFavoritos.setBackground(new java.awt.Color(102, 102, 102));
        pnlMisFavoritos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlElementosFav.setBackground(new java.awt.Color(51, 51, 51));

        cmbFiltroTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Albumes", "Artistas", "Canciones" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genero" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mas reciente" }));

        jLabel2.setText("Elementos");

        javax.swing.GroupLayout pnlElementosFavLayout = new javax.swing.GroupLayout(pnlElementosFav);
        pnlElementosFav.setLayout(pnlElementosFavLayout);
        pnlElementosFavLayout.setHorizontalGroup(
            pnlElementosFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlElementosFavLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlElementosFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(pnlElementosFavLayout.createSequentialGroup()
                        .addComponent(cmbFiltroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        pnlElementosFavLayout.setVerticalGroup(
            pnlElementosFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlElementosFavLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlElementosFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFiltroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnlElementosFav);

        pnlMisFavoritos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 580, 260));

        pnlFavoritos.add(pnlMisFavoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 640, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFavoritos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFavoritos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbFiltroTipo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private buscador.Buscador pnlBuscador;
    private javax.swing.JPanel pnlElementosFav;
    private javax.swing.JPanel pnlFavoritos;
    private javax.swing.JPanel pnlMisFavoritos;
    // End of variables declaration//GEN-END:variables
}
