/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package detalles;

import buscador.Buscador;
import control.ControlNavegacion;
import java.awt.Component;

/**
 *
 * @author jalt2
 */
public class DetalleAlbum extends javax.swing.JFrame {
    private ControlNavegacion controlNavegacion;
    /**
     * Creates new form DetalleAlbum
     */
    public DetalleAlbum(ControlNavegacion controlNavegacion) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controlNavegacion=controlNavegacion;
        this.controlNavegacion.agregarClickListeners(this, pnlBuscador.getTxtBuscar());
        
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel1 = new javax.swing.JPanel();
        pnlDetalleAlbum = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblGeneros = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel5 = new javax.swing.JLabel();
        lblIntegrantes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlBuscador = new buscador.Buscador();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jpanel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                Jpanel1ComponentAdded(evt);
            }
        });

        pnlDetalleAlbum.setBackground(new java.awt.Color(102, 102, 102));
        pnlDetalleAlbum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Detalle del Album");
        pnlDetalleAlbum.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 25, -1, -1));

        jLabel3.setText("Imagen");
        pnlDetalleAlbum.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 75, -1, -1));

        lblArtista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblArtista.setText("Nombre Album");
        pnlDetalleAlbum.add(lblArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 64, -1, -1));

        lblGeneros.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblGeneros.setText("Genero/s: ");
        pnlDetalleAlbum.add(lblGeneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 95, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlDetalleAlbum.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 350, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, 100));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Canciones");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pnlDetalleAlbum.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 380, 120));

        lblIntegrantes.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblIntegrantes.setText("Lanzamiento:");
        pnlDetalleAlbum.add(lblIntegrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1.setText("Autor:");
        pnlDetalleAlbum.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        javax.swing.GroupLayout Jpanel1Layout = new javax.swing.GroupLayout(Jpanel1);
        Jpanel1.setLayout(Jpanel1Layout);
        Jpanel1Layout.setHorizontalGroup(
            Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel1Layout.createSequentialGroup()
                .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(pnlDetalleAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Jpanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Jpanel1Layout.setVerticalGroup(
            Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(pnlBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDetalleAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jpanel1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Jpanel1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Jpanel1ComponentAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblGeneros;
    private javax.swing.JLabel lblIntegrantes;
    private buscador.Buscador pnlBuscador;
    private javax.swing.JPanel pnlDetalleAlbum;
    // End of variables declaration//GEN-END:variables
}
